# Generated by Django 5.1.1 on 2024-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_estado_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='peticion',
            options={'verbose_name': 'Petición', 'verbose_name_plural': 'Peticiones'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
