# Generated by Django 5.1.1 on 2024-10-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_pedido_options_remove_pedido_comida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='plato',
        ),
        migrations.AlterModelOptions(
            name='peticion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RenameField(
            model_name='peticion',
            old_name='dia_reserva',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='peticion',
            name='num_personas',
        ),
        migrations.AddField(
            model_name='peticion',
            name='numero_personas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='peticion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.peticion'),
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Platos',
        ),
    ]
