# Generated by Django 5.1.1 on 2024-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_platos_precio_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='precio_plato',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
