# Generated by Django 5.1.1 on 2024-10-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_alter_platos_precio_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='precio_plato',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Pedidos_recoger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=50)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.platos')),
            ],
            options={
                'verbose_name': 'Pedido para recoger',
                'verbose_name_plural': 'Pedidos para recoger',
            },
        ),
    ]
