# Generated by Django 5.1.1 on 2024-10-08 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_platos_precio_plato_pedidos_recoger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos_recoger',
            new_name='Pedidos',
        ),
    ]
