# Generated by Django 5.1.1 on 2024-10-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_rename_pedidos_recoger_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='plato',
        ),
        migrations.CreateModel(
            name='PedidoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_platos', to='reservas.pedidos')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.platos')),
            ],
            options={
                'verbose_name': 'Plato en Pedido',
                'verbose_name_plural': 'Platos en Pedido',
            },
        ),
    ]
