# Generated by Django 5.1.1 on 2024-10-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_remove_reserva_peticion_delete_peticion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPlatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_plato', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valoracion', models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0)),
                ('nombre_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_platos', to='reservas.platos')),
            ],
            options={
                'verbose_name': 'Catálogo de Plato',
                'verbose_name_plural': 'Catálogo de Platos',
            },
        ),
    ]
