# Generated by Django 5.1.1 on 2024-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0023_pedidos_platos'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoplatos',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
