# Generated by Django 5.1.1 on 2024-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_catalogoplatos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoplato',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
