# Generated by Django 5.1.1 on 2024-10-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoplatos',
            old_name='nombre_plato',
            new_name='plato',
        ),
    ]
