# Generated by Django 5.1.1 on 2024-10-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0027_rename_nombre_plato_catalogoplatos_plato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogoplatos',
            old_name='plato',
            new_name='nombre_plato',
        ),
    ]
