# Generated by Django 5.1.2 on 2024-10-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0029_rename_nombre_plato_catalogoplatos_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ingrediente', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='platos',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='platos', to='reservas.ingrediente'),
        ),
    ]
