# Generated by Django 5.1.2 on 2024-10-15 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0031_tipo_ingrediente_ingrediente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='reservas.ingrediente'),
        ),
    ]
