# Generated by Django 5.1.2 on 2024-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0034_bebidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='precio_bebida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
