# Generated by Django 5.1.2 on 2024-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0035_bebidas_precio_bebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_bebida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo bebida',
                'verbose_name_plural': 'Tipos de bebidas',
            },
        ),
        migrations.AddField(
            model_name='bebidas',
            name='tipo_bebi',
            field=models.ManyToManyField(blank=True, related_name='bebidas', to='reservas.tipo_bebida'),
        ),
    ]
