# Generated by Django 5.1.2 on 2024-10-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0036_tipo_bebida_bebidas_tipo_bebi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo comida',
                'verbose_name_plural': 'Tipos de comidas',
            },
        ),
        migrations.AlterField(
            model_name='platos',
            name='ingredientes',
            field=models.ManyToManyField(to='reservas.ingrediente'),
        ),
        migrations.AlterField(
            model_name='platos',
            name='precio_plato',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='platos',
            name='tipo_comida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservas.tipo_comida'),
        ),
    ]
