# Generated by Django 5.1.2 on 2024-10-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0039_mispedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='mispedidos',
            old_name='pedido_platos',
            new_name='platos',
        ),
        migrations.RemoveField(
            model_name='mispedidos',
            name='nombre_persona',
        ),
        migrations.AddField(
            model_name='mispedidos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.estadopedido'),
        ),
    ]
