# Generated by Django 5.1.2 on 2024-10-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0040_estadopedido_rename_pedido_platos_mispedidos_platos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mispedidos',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mispedidos',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='mispedidos',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EstadoPedido',
        ),
        migrations.DeleteModel(
            name='MisPedidos',
        ),
    ]
