# Generated by Django 5.1.2 on 2024-10-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0042_estadopedido_mispedidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MisPedidos',
        ),
    ]
