# Generated by Django 5.1.2 on 2024-10-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0043_delete_mispedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='platos',
        ),
        migrations.CreateModel(
            name='MisPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.platos')),
            ],
            options={
                'verbose_name': 'Pedido para recoger',
                'verbose_name_plural': 'Pedidos para recoger',
            },
        ),
        migrations.DeleteModel(
            name='PedidoPlato',
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
