# Generated by Django 5.1.2 on 2024-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0044_remove_pedidos_platos_mispedidos_delete_pedidoplato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platos',
            name='valoracion',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0),
        ),
        migrations.DeleteModel(
            name='CatalogoPlatos',
        ),
    ]
