# Generated by Django 5.1.2 on 2024-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0049_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='valoracion',
            field=models.IntegerField(choices=[(0, '☆☆☆☆☆'), (1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=0),
        ),
    ]
