# Generated by Django 5.1.2 on 2024-10-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0050_bebidas_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bebidas',
            name='valoracion',
        ),
    ]
