# Generated by Django 5.1.2 on 2024-11-06 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0055_remove_platos_comentarios_remove_platos_valoracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='reservas.ingrediente'),
        ),
        migrations.CreateModel(
            name='PedidoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.mispedidos')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.platos')),
            ],
        ),
    ]
