# Generated by Django 5.1.2 on 2024-11-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0056_alter_platos_ingredientes_pedidoplato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mispedidos',
            name='plato',
        ),
        migrations.AddField(
            model_name='mispedidos',
            name='platos',
            field=models.ManyToManyField(through='reservas.PedidoPlato', to='reservas.platos'),
        ),
    ]
