# Generated by Django 5.1.2 on 2024-11-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0059_alter_mispedidos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mispedidos',
            name='plato',
        ),
        migrations.AddField(
            model_name='mispedidos',
            name='platos',
            field=models.ManyToManyField(related_name='mis_pedidos', to='reservas.platos'),
        ),
    ]
