# Generated by Django 5.1.2 on 2024-11-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0060_remove_mispedidos_plato_mispedidos_platos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mispedidos',
            name='platos',
        ),
        migrations.AddField(
            model_name='mispedidos',
            name='plato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservas.platos'),
        ),
    ]
